### ISSUE TITLE
org.litepal.exceptions.LitePalSupportException: Expression tree is too large (maximum depth 1000)

### ISSUE THREAD

**Issue by rx1996** [guolindev/LitePal#724]
在调用save的过程中出现了这个异常，请问如何解除这个限制？

**Comment by guolindev** [comment]
这个限制无法接触，这不是LitePal是限制，而是SQLite的限制。
出现这个错误说明你的SQL语句太复杂了，导致SQL引擎无法解析。
是不是你save的对象字段过多，正常情况下一般是不会出现这种错误的。

**Comment by rx1996** [comment]
好的，谢谢，我已经解决了

**Comment by dijiubuzhan** [comment]
郭神，我现在的业务逻辑中一个litepal有个list集合字段，当集合大于1000时就会保存，看了代码是由于匹配list字段时使用了1000个以上的or导致的，实际上这些id是连续的，可以用between表达式的，但是litepal暂时不支持，这个怎么解决哇？
`09-30 12:17:04.029 20404 21072 E SQLiteLog: (1) Expression tree is too large (maximum depth 1000) in "UPDATE commandexecuteinfo SET taskcasefinishedinfo_id=? WHERE id = 14336 or id = 14337 or id = 14338 or id = 14339 or id = 14340 or id = 14341 or id = 1434
09-30 12:17:04.035 20404 21072 W System.err: com.shan.litepal.exceptions.LitePalSupportException: Expression tree is too large (maximum depth 1000) (code 1 SQLITE_ERROR): , while compiling: UPDATE commandexecuteinfo SET taskcasefinishedinfo_id=? WHERE id = 14336 or id = 14337 or id = 14338 or id = 14339 or id = 14340 or id = 14341 or id = 14342 or id = 14343 or id = 14344 or id = 14345 or id = 14346 or id = 14347 or id = 14348 or id = 14349 or id = 14350 or id = 14351 or id = 14352 or id = 14353 or id = 14354 or id = 14355 or id = 14356 or id = 14357 or id = 14358 or id = 14359 or id = 14360 or id = 14361 or id = 14362 or id = 14363 or id = 14364 or id = 14365 or id = 14366 or id = 14367 or id = 14368 or id = 14369 or id = 14370 or id = 14371 or id = 14372 or id = 14373 or id = 14374 or id = 14375 or id = 14376 or id = 14377 or id = 14378 or id = 14379 or id = 14380 or id = 14381 or id = 14382 or id = 14383 or id = 14384 or id = 14385 or id = 14386 or id = 14387 or id = 14388 or id = 14389 or id = 14390 or id = 14391 or id = 14392 or id = 14393 or id = 14394 or id = 14395 or id = 14396 or id = 14397 or id = 14398 or id = 14399 or id = 14400 or id = 14401 or id = 14402 or id = 14403 or id = 14404 or id = 14405 or id = 14406 or id = 14407 or id = 14408 or id = 14409 or id = 14410 or id = 14411 or id = 14412 or id = 14413 or id = 14414 or id = 14415 or id = 14416 or id = 14417 or id = 14418 or id = 14419 or id = 14420 or id = 14421 or id = 14422 or id = 14423 or id = 14424 or id = 14425 or id = 14426 or id = 14427 or id = 14428 or id = 14429 or id = 14430 or id = 14431 or id = 14432 or id = 14433 or id = 14434 or id = 14435 or id = 14436 or id = 14437 or id = 14438 or id = 14439 or id = 14440 or id = 14441 or id = 14442 or id = 14443 or id = 14444 or id = 14445 or id = 14446 or id = 14447 or id = 14448 or id = 14449 or id = 14450 or id = 14451 or id = 14452 or id = 14453 or id = 14454 or id = 14455 or id = 14456 or id = 14457 or id = 14458 or id = 14459 or id = 14460 or id = 14461 or id = 14462 or id = 14463 or id = 14464 or id = 14465 or id = 14466 or id = 14467 or id = 14468 or id = 14469 or id = 14470 or id = 14471 or id = 14472 or id = 14473 or id = 14474 or id = 14475 or id = 14476 or id = 14477 or id = 14478 or id = 14479 or id = 14480 or id = 14481 or id = 14482 or id = 14483 or id = 14484 or id = 14485 or id = 14486 or id = 14487 or id = 14488 or id = 14489 or id = 14490 or id = 14491 or id = 14492 or id = 14493 or id = 14494 or id = 14495 or id = 14496 or id = 14497 or id = 14498 or id = 14499 or id = 14500 or id = 14501 or id = 14502 or id = 14503 or id = 14504 or id = 14505 or id = 14506 or id = 14507 or id = 14508 or id = 14509 or id = 14510 or id = 14511 or id = 14512 or id = 14513 or id = 14514 or id = 14515 or id = 14516 or id = 14517 or id = 14518 or id = 14519 or id = 14520 or id = 14521 or id = 14522 or id = 14523 or id = 14524 or id = 14525 or id = 14526 or id = 14527 or id = 14528 or id = 14529 or id = 14530 or id = 14531 or id = 14532 or id = 14533 or id = 14534 or id = 14535 or id = 14536 or id = 14537 or id = 14538 or id = 14539 or id = 14540 or id = 14541 or id = 14542 or id = 14543 or id = 14544 or id = 14545 or id = 14546 or id = 14547 or id = 14548 or id = 14549 or id = 14550 or id = 14551 or id = 14552 or id = 14553 or id = 14554 or id = 14555 or id = 14556 or id = 14557 or id = 14558 or id = 14559 or id = 14560 or id = 14561 or id = 14562 or id = 14563 or id = 14564 or id = 14565 or id = 14566 or id = 14567 or id = 14568 or id = 14569 or id = 14570 or id = 14571 or id = 14572 or id = 14573 or id = 14574 or id = 14575 or id = 14576 or id = 14577 or id = 14578 or id = 14579 or id = 14580 or id = 14581 or id = 14582 or id = 14583 or id = 14584 or id = 14585 or id = 14586 or id = 14587 or id = 14588 or id = 14589 or id = 14590 or id = 14591 or id = 14592 or id = 14593 or id = 14594 or id = 14595 or id = 14596 or id = 14597 or id = 14598 or id = 14599 or id = 14600 or id = 14601 or id = 14602 or id = 14603 or id = 14604 or id = 14605 or id = 14606 or id = 14607 or id = 14608 or id = 14609 or id = 146
09-30 12:17:04.036 20404 21072 W System.err: 	at com.shan.litepal.crud.LitePalSupport.saveThrows(LitePalSupport.java:403)
09-30 12:17:04.036 20404 21072 W System.err: 	at com.shan.litepal.crud.LitePalSupport.save(LitePalSupport.java:334)
09-30 12:17:04.036 20404 21072 W System.err: 	at com.shan.yun.info.TaskCaseFinishedInfo.save(TaskCaseFinishedInfo.java:62)
09-30 12:17:04.036 20404 21072 W System.err: 	at com.shan.yun.class.if.dT(ScriptExcuteThread.java:1765)
09-30 12:17:04.036 20404 21072 W System.err: 	at com.shan.yun.class.if.zK(ScriptExcuteThread.java:2754)
09-30 12:17:04.036 20404 21072 W System.err: 	at com.shan.yun.class.if.run(ScriptExcuteThread.java:2598)
09-30 12:17:04.038 20404 21072 W System.err: Caused by: android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000) (code 1 SQLITE_ERROR): , while compiling: UPDATE commandexecuteinfo SET taskcasefinishedinfo_id=? WHERE id = 14336 or id = 14337 or id = 14338 or id = 14339 or id = 14340 or id = 14341 or id = 14342 or id = 14343 or id = 14344 or id = 14345 or id = 14346 or id = 14347 or id = 14348 or id = 14349 or id = 14350 or id = 14351 or id = 14352 or id = 14353 or id = 14354 or id = 14355 or id = 14356 or id = 14357 or id = 14358 or id = 14359 or id = 14360 or id = 14361 or id = 14362 or id = 14363 or id = 14364 or id = 14365 or id = 14366 or id = 14367 or id = 14368 or id = 14369 or id = 14370 or id = 14371 or id = 14372 or id = 14373 or id = 14374 or id = 14375 or id = 14376 or id = 14377 or id = 14378 or id = 14379 or id = 14380 or id = 14381 or id = 14382 or id = 14383 or id = 14384 or id = 14385 or id = 14386 or id = 14387 or id = 14388 or id = 14389 or id = 14390 or id = 14391 or id = 14392 or id = 14393 or id = 14394 or id = 14395 or id = 14396 or id = 14397 or id = 14398 or id = 14399 or id = 14400 or id = 14401 or id = 14402 or id = 14403 or id = 14404 or id = 14405 or id = 14406 or id = 14407 or id = 14408 or id = 14409 or id = 14410 or id = 14411 or id = 14412 or id = 14413 or id = 14414 or id = 14415 or id = 14416 or id = 14417 or id = 14418 or id = 14419 or id = 14420 or id = 14421 or id = 14422 or id = 14423 or id = 14424 or id = 14425 or id = 14426 or id = 14427 or id = 14428 or id = 14429 or id = 14430 or id = 14431 or id = 14432 or id = 14433 or id = 14434 or id = 14435 or id = 14436 or id = 14437 or id = 14438 or id = 14439 or id = 14440 or id = 14441 or id = 14442 or id = 14443 or id = 14444 or id = 14445 or id = 14446 or id = 14447 or id = 14448 or id = 14449 or id = 14450 or id = 14451 or id = 14452 or id = 14453 or id = 14454 or id = 14455 or id = 14456 or id = 14457 or id = 14458 or id = 14459 or id = 14460 or id = 14461 or id = 14462 or id = 14463 or id = 14464 or id = 14465 or id = 14466 or id = 14467 or id = 14468 or id = 14469 or id = 14470 or id = 14471 or id = 14472 or id = 14473 or id = 14474 or id = 14475 or id = 14476 or id = 14477 or id = 14478 or id = 14479 or id = 14480 or id = 14481 or id = 14482 or id = 14483 or id = 14484 or id = 14485 or id = 14486 or id = 14487 or id = 14488 or id = 14489 or id = 14490 or id = 14491 or id = 14492 or id = 14493 or id = 14494 or id = 14495 or id = 14496 or id = 14497 or id = 14498 or id = 14499 or id = 14500 or id = 14501 or id = 14502 or id = 14503 or id = 14504 or id = 14505 or id = 14506 or id = 14507 or id = 14508 or id = 14509 or id = 14510 or id = 14511 or id = 14512 or id = 14513 or id = 14514 or id = 14515 or id = 14516 or id = 14517 or id = 14518 or id = 14519 or id = 14520 or id = 14521 or id = 14522 or id = 14523 or id = 14524 or id = 14525 or id = 14526 or id = 14527 or id = 14528 or id = 14529 or id = 14530 or id = 14531 or id = 14532 or id = 14533 or id = 14534 or id = 14535 or id = 14536 or id = 14537 or id = 14538 or id = 14539 or id = 14540 or id = 14541 or id = 14542 or id = 14543 or id = 14544 or id = 14545 or id = 14546 or id = 14547 or id = 14548 or id = 14549 or id = 14550 or id = 14551 or id = 14552 or id = 14553 or id = 14554 or id = 14555 or id = 14556 or id = 14557 or id = 14558 or id = 14559 or id = 14560 or id = 14561 or id = 14562 or id = 14563 or id = 14564 or id = 14565 or id = 14566 or id = 14567 or id = 14568 or id = 14569 or id = 14570 or id = 14571 or id = 14572 or id = 14573 or id = 14574 or id = 14575 or id = 14576 or id = 14577 or id = 14578 or id = 14579 or id = 14580 or id = 14581 or id = 14582 or id = 14583 or id = 14584 or id = 14585 or id = 14586 or id = 14587 or id = 14588 or id = 14589 or id = 14590 or id = 14591 or id = 14592 or id = 14593 or id = 14594 or id = 14595 or id = 14596 or id = 14597 or id = 14598 or id = 14599 or id = 14600 or id = 14601 or id = 14602 or id = 14603 or id = 14604 or id = 14605 or id = 14606 or id = 14607 or id = 14608 or id = 14609 or id = 14610 or
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1804)
09-30 12:17:04.038 20404 21072 W System.err: 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1752)
09-30 12:17:04.038 20404 21072 W System.err: 	at com.shan.litepal.crud.SaveHandler.updateAssociatedTableWithFK(SaveHandler.java:409)
09-30 12:17:04.038 20404 21072 W System.err: 	at com.shan.litepal.crud.SaveHandler.afterSave(SaveHandler.java:203)
09-30 12:17:04.038 20404 21072 W System.err: 	at com.shan.litepal.crud.SaveHandler.doSaveAction(SaveHandler.java:142)
09-30 12:17:04.038 20404 21072 W System.err: 	at com.shan.litepal.crud.SaveHandler.onSave(SaveHandler.java:67)
09-30 12:17:04.038 20404 21072 W System.err: 	at com.shan.litepal.crud.LitePalSupport.saveThrows(LitePalSupport.java:399)
09-30 12:17:04.038 20404 21072 W System.err: 	... 5 more`
